In [1]:
from numpy import *


In [2]:
X = random.randn(200,2)

In [9]:
Y = ones((200,1))

In [10]:
Y[101:200,0] = 2

In [11]:
Y

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [19]:
a_tmp = ((Y.T.dot(X[:,1]))**2)/(X[:,1].T.dot(X[:,1]))

In [14]:
a_max = -1

In [20]:
a_tmp

array([ 10.51267346])

In [21]:
if a_tmp > a_max:
    print('this')

this


In [24]:
I = []
j = 2
I.append(j)

In [25]:
I

[2]

In [26]:
A = random.rand(2,2)

In [29]:
linalg.pinv(A).dot(A)

array([[  1.00000000e+00,   0.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00]])

In [30]:
help(ceil)

Help on ufunc object:

ceil = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y, o

In [32]:
Xtr = random.randn(200,30)
Ytr = ones((200,1))
Ytr[100:] = -1
Ytr

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [34]:
w = zeros((30,1))
w[0] = 0.8
w

array([[ 0.8],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ]])

In [35]:
def calculateErr(T, Y):
    vT = (T >= 0);
    vY = (Y >= 0);
    err = sum(vT != vY)/size(Y);
    return err

In [36]:
calculateErr(Xtr.dot(w), Ytr)

0.45500000000000002

In [41]:
str = ('rip\\tIter\\tvalErr\\ttrErr\\n%d\\t%d\\t%f\\t%f\\n'), rip, it, vmn(iit, rip), tmn(iit, rip); print (str)

NameError: name 'rip' is not defined

In [43]:
def calcErr(T, Y):
    err = mean(sign(T)!=sign(Y));
    return err

In [44]:
calcErr(Xtr.dot(w), Ytr)

0.45500000000000002

In [45]:
def PCA(X, k):
# [V, d, X_proj] = PCA(X, k)
# computes the first k eigenvectors, eigenvalues and projections of the 
# matrix X'*X/n where n is the number of rows in X.
# 
# X is the dataset
# k is the number of components
# 
# V is a matrix of the form [v_1, ..., v_k] where v_i is the i-th
# eigenvector
# d is the list of the first k eigenvalues
# X_proj is the projection of X on the linear space spanned by the
# eigenvectors in V
    
    numRowsOfX = X.shape[0]
    D, V = scipy.sparse.linalg.eigs((X.conj().transpose().dot(X))/numRowsOfX, k)
#     diagonal = diag(D)
    D = D * (D > 0)
#     D = sorted(D, reverse = True)
    D[::-1].sort()
    I = D.argsort()
    V = V[:, I]
    X_proj = X.dot(V)
    
    return V, D, X_proj

In [46]:
def OMatchingPursuit(inputData, outputLabel, numOfIter):
# X = array([[1.,2.,3.], [4.,5.,6.]])
# row, col = shape(X)
    numOfRow, numOfCol = shape(inputData)
    residual = outputLabel
    estimatedCoeff = zeros((numOfCol, 1))
    indices = []
    
    for i in range(numOfIter):
        indices_tmp = list(range(numOfRow))
        
        ### Select the column of X which most "explains" the residual
        a_max = -1
        
        for j in indices_tmp:
#             a_tmp = ((residual.T * X[:,1])**2)/(X[:,1].T * X[:,1])
            a_tmp = ((residual.T.dot(inputData[:,1]))**2)/(inputData[:,1].T.dot(inputData[:,1]))
            
            if a_tmp > a_max:
                a_max = a_tmp
                j_max = j
                
        # Add the index to the set of indexes
        if sum(indices == j_max) == 0:
            indices.append(j_max)
            
        # Compute the M matrix
        M_I = zeros((numOfCol,numOfCol))
                    
        for j in indices:
            M_I[j,j] = 1
                   
        A = M_I.dot(inputData.T).dot(inputData).dot(M_I)
        B = M_I.dot(inputData.T).dot(outputLabel)
        
        # Update estimated coefficients
        estimatedCoeff = linalg.pinv(A).dot(B)
        
        # Update the residual
        residual = outputLabel - inputData.dot(estimatedCoeff)
        
        return estimatedCoeff, residual, indices
            

In [47]:
def holdoutCVOMP(X, Y, perc, nrip, intIter):
    nIter = size(intIter)
    
    n = X.shape[0]
    ntr = ceil(n*(1-perc))
    
    tmn = zeros((nIter, nrip))
    vmn = zeros((nIter, nrip))
    
    for rip in range(nrip):
        I = random.permutation(n)
        Xtr = X[I[:ntr],:]
        Ytr = Y[I[:ntr],:]
        Xvl = X[I[ntr:],:]
        Yvl = Y[I[ntr:],:]
        
        iit = 0
        
        for it in range(intIter):
            iit = iit + 1;
            w = OMatchingPursuit(Xtr, Ytr, it)
            tmn[iit, rip] =  calcErr(Xtr.dot(w),Ytr)
            vmn[iit, rip]  = calcErr(Xvl.dot(w),Yvl)
            
            print(('rip\\tIter\\tvalErr\\ttrErr\\n%d\\t%d\\t%f\\t%f\\n'), rip, it, vmn(iit, rip), tmn(iit, rip))
            
    Tm = median(tmn,axis=1);
    Ts = std(tmn,axis=1);
    Vm = median(vmn,axis=1);
    Vs = std(vmn,axis=1);
    
    row = nonzero(Vm <= min(min(Vm)));
    
    it = intIter[row[0]]
    
    return it, Vm, Vs, Tm, Ts

In [ ]:
N = 100;
D = 30;
Xtr, Ytr = MixGauss([[1;1],[-1;1]],[0.7,0.7],N);
Ytr[Ytr==2]= -1;
[Xts, Yts] = MixGauss([[1;1],[-1;1]],[0.7,0.7],N);
Yts(Yts==2) = -1;

In [3]:
n = 10
print('number ',n)

number  10
